linters:
  enable-all: true
  disable:
    - depguard
    - tagliatelle
    - ireturn
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gofumpt
    - forbidigo
    # depricated
    - exhaustruct
    - tenv

issues:
  exclude-files:
    - ".*_test.go$"

linters-settings:
  wrapcheck:
    # An array of strings that specify substrings of signatures to ignore.
    # If this set, it will override the default set of ignored signatures.
    # See https://github.com/tomarrell/wrapcheck#configuration for more information.
    # Default: [".Errorf(", "errors.New(", "errors.Unwrap(", ".Wrap(", ".Wrapf(", ".WithMessage(", ".WithMessagef(", ".WithStack("]
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      - multierror.Append(
      - .ErrorOrNil()

  varnamelen:
    # The longest distance, in source lines, that is being considered a "small scope".
    # Variables used in at most this many lines will be ignored.
    # Default: 5
    max-distance: 12
    ignore-decls:
      - t testing.T
      - T any
      - tr trace.Trace
    ignore-names:
      - wg
      - rx
      - tx
      - re
      - ch

  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    # Default is to use a neutral variety of English.
    locale: US
    # Default: []
    ignore-words:
      - routeros

  gocritic:
    disabled-checks:
