version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - ireturn
    - tagliatelle
  settings:
    misspell:
      locale: US
      ignore-rules:
        - routeros
    varnamelen:
      max-distance: 12
      ignore-names:
        - wg
        - rx
        - tx
        - re
        - ch
      ignore-decls:
        - t testing.T
        - T any
        - tr trace.Trace
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        - multierror.Append(
        - .ErrorOrNil()
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*_test.go$
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
    - gci
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - .*_test.go$
      - third_party$
      - builtin$
      - examples$
