devices:
  - name: dev1
    address: 192.168.0.1
    # default for non-ssl
    port: 8728
    user: ro
    password: ro
    profile: router
    # disable ipv6 metrics for this device
    ipv6_disabled: true
    # by default device is enabled
    disabled: false

    # configuration for firewall collector
    fw_collector_settings:
      # collect metric from `filter`
      filter:
        # and from chain `input`
        - input
      nat:
        - srcnat

    # script to run by scripts collector
    scripts:
      - script1

  - name: dev2
    address: 192.168.0.2
    # enable ssl
    tls: true
    # default for tls
    port: 8729
    # do not verify certificates
    insecure: true
    user: ro
    password: ro
    profile: basic
    # device is disabled
    disabled: true
  - name: dev3
    address: dev3
    user: ro
    password: ro
    # use default profile
    # profile: basic


# default features (profile)
features:
  # enable capsman
  arp:
    # disable metrics for each arp entry; keep only stats (default)
    details: false
  # enable capsman
  capsman:
    # disable metric for each registered station (default)
    stations: false
  certs: true
  cloud: true
  conntrack: true
  dhcp: true
  dhcpl:
    # disable details - count only number of lease in each state (default)
    details: false
  dhcpv6: true
  disk: true
  dns: false
  # disable dns_adlist in 'new' format
  dns_adlist:
    enabled: false
  dude: false
  firewall: true
  firmware: true
  health: true
  interface: true
  ip: true
  ipsec: true
  # collect /ipv6 neighbor metrics
  ipv6_neighbor:
    # disable details - count only entries in each status
    details: false
  lte: true
  monitor: true
  neighbor:
    # disable details - count only neighbours discovered by interface
    details: false
  netwatch: true
  # enable metrics from ntp client
  ntpc:
  optics: true
  poe: true
  pools: true
  queue: true
  routes: true
  scripts: false
  service: false
  w60g: true
  wireguard:
    # disable details; count only connected/waitine peers
    details: false
  wlanif: true
  # new format (v2) - dictionary of values
  wlansta:
    enabled: true
  # always captured
  resource: true

# custom profiles
profiles:
  router:
    arp:
      # enable metrics for each arp entry
      details: true
    capsman: true
    certs: true
    cloud: true
    conntrack: true
    dhcp: true
    dhcpl: true
    firewall: true
    health: true
    monitor: true
    netwatch: true
    ntpc: true
    poe: true
    pools: true
    queue: true
    resource: true
    routes: true
    wlanif: true
  basic:
    cloud: true
    conntrack: true
    health: true
    monitor: true
    netwatch: true
    resource: true
    wlanif: true
