devices:
  - name: dev1
    address: 192.168.0.1
    # default for non-ssl
    port: 8728
    user: ro
    password: ro
    profile: router
    # disable ipv6 metrics for this device
    ipv6_disabled: true
    # by default device is enabled
    disabled: false

    # configuration for firewall collector
    fw_collector_settings:
      # collect metric from `filter`
      filter:
        # and from chain `input`
        - input
      nat:
        - srcnat

    # script to run by scripts collector
    scripts:
      - script1

  - name: dev2
    address: 192.168.0.2
    # enable ssl
    tls: true
    # default for tls
    port: 8729
    # do not verify certificates
    insecure: true
    user: ro
    password: ro
    profile: basic
    # device is disabled
    disabled: true
  - name: dev3
    address: dev3
    user: ro
    password: ro
    # use default profile
    # profile: basic


# default features (profile)
features:
  arp: false
  capsman: true
  certs: true
  cloud: true
  conntrack: true
  dhcp: true
  dhcpl: true
  dhcpv6: true
  disk: true
  dns: false
  dns_adlist: false
  dude: false
  firewall: true
  firmware: true
  health: true
  interface: true
  ip: true
  ipsec: true
  lte: true
  monitor: true
  neighbor: false
  netwatch: true
  optics: true
  poe: true
  pools: true
  queue: true
  routes: true
  scripts: false
  service: false
  w60g: true
  wlanif: true
  # new format (v2) - dictionary of values
  wlansta:
    enabled: true
  # always captured
  resource: true

# custom profiles
profiles:
  router:
    capsman: true
    certs: true
    cloud: true
    conntrack: true
    dhcp: true
    dhcpl: true
    firewall: true
    health: true
    monitor: true
    netwatch: true
    poe: true
    pools: true
    queue: true
    resource: true
    routes: true
    wlanif: true
  basic:
    cloud: true
    conntrack: true
    health: true
    monitor: true
    netwatch: true
    resource: true
    wlanif: true
