{
 "title": "Routeros",
 "tags": [
  "mikrotik",
  "routeros"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "devname",
    "label": "Device",
    "query": {
     "query": "label_values(mikrotik_system_routeros,dev_name)"
    }
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": {
     "query": "label_values(mikrotik_interface_running{dev_name=~\"$devname\"},interface)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RouterOS",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "mikrotik_system_routeros{dev_name=~\"$devname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - mikrotik_system_start_time_seconds{dev_name=~\"$devname\"}",
     "legendFormat": "uptime {{dev_name}}"
    }
   ]
  },
  {
   "title": "Certs",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "mikrotik_cert_invalid_after{dev_name=~\"$devname\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mikrotik_system_cpu_load{dev_name=~\"$devname\"}",
     "legendFormat": "{{dev_name}}"
    }
   ]
  },
  {
   "title": "Used  Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-mikrotik_system_free_memory{dev_name=~\"$devname\"} / mikrotik_system_total_memory{dev_name=~\"$devname\"}",
     "legendFormat": "{{dev_name}}"
    }
   ]
  },
  {
   "title": "Storage used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-mikrotik_system_free_hdd_space{dev_name=~\"$devname\"} / mikrotik_system_total_hdd_space{dev_name=~\"$devname\"}",
     "legendFormat": "{{dev_name}}"
    }
   ]
  },
  {
   "title": "temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "mikrotik_health_temperature{dev_name=~\"$devname\"}",
     "legendFormat": "{{dev_name}}"
    }
   ]
  },
  { "title": "Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Bytes All Interfaces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(mikrotik_interface_rx_byte_total{interface!=\"lo\", dev_name=~\"$devname\"}[$__rate_interval]))",
     "legendFormat": "tx"
    },
    {
     "expr": "sum(rate(mikrotik_interface_tx_byte_total{interface!=\"lo\", dev_name=~\"$devname\"}[$__rate_interval]))",
     "legendFormat": "rx"
    }
   ]
  },
  {
   "title": "Packets All Interfaces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(mikrotik_interface_rx_packet_total{interface!=\"lo\", dev_name=~\"$devname\"}[$__rate_interval]))",
     "legendFormat": "rx"
    },
    {
     "expr": "sum(rate(mikrotik_interface_tx_packet_total{interface!=\"lo\", dev_name=~\"$devname\"}[$__rate_interval]))",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Drop All Interfaces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(mikrotik_interface_rx_drop_total{interface!=\"lo\", dev_name=~\"$devname\"}[$__rate_interval]))   ",
     "legendFormat": "rx"
    },
    {
     "expr": "sum(rate(mikrotik_interface_tx_drop_total{interface!=\"lo\", dev_name=~\"$devname\"}[$__rate_interval]))",
     "legendFormat": "tx"
    },
    {
     "expr": "sum(rate(mikrotik_interface_tx_queue_drop_total{interface!=\"lo\", dev_name=~\"$devname\"}[$__rate_interval]))",
     "legendFormat": "tx queue drop"
    }
   ]
  },
  {
   "title": "Error All Interfaces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(mikrotik_interface_rx_error_total{interface!=\"lo\", dev_name=~\"$devname\"}[$__rate_interval]))",
     "legendFormat": "rx"
    },
    {
     "expr": "sum(rate(mikrotik_interface_tx_error_total{interface!=\"lo\", dev_name=~\"$devname\"}[$__rate_interval]))",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "WIFI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "noise floor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "mikrotik_wlan_interface_noise_floor{dev_name=~\"$devname\"}",
       "legendFormat": "{{dev_name}} {{interface}}"
      }
     ]
    },
    {
     "title": "Overall Tx CCQ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "mikrotik_wlan_interface_overall_tx_ccq{dev_name=~\"$devname\"}",
       "legendFormat": "{{name}} {{interface}}"
      }
     ]
    },
    {
     "title": "WIFI Channels",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 153 },
     "targets": [
      {
       "expr": "mikrotik_wlan_interface_channel{dev_name=~\"$devname\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "IP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "DDNS Enabled",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(mikrotik_cloud_ddns_enabled{dev_name=~\"$devname\"} == 1) / count(mikrotik_cloud_ddns_enabled{dev_name=~\"$devname\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "cloud updated",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 2, "x": 2, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(mikrotik_cloud_status{dev_name=~\"$devname\", status=\"updated\"}) / count(mikrotik_cloud_status{dev_name=~\"$devname\"})",
       "legendFormat": "updated"
      }
     ]
    },
    {
     "title": "BTH VPN Enabled",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 2, "x": 4, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(mikrotik_cloud_bth_vpn_enabled{dev_name=~\"$devname\"} == 1) / count(mikrotik_cloud_bth_vpn_enabled{dev_name=~\"$devname\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "BTH VPN Relay reachable",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 2, "x": 6, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(mikrotik_cloud_bth_vpn_relay_ipv4_reachable{dev_name=~\"$devname\"} == 1) / count(mikrotik_cloud_bth_vpn_relay_ipv4_reachable{dev_name=~\"$devname\"})) or vector(0)",
       "legendFormat": "IPv4"
      },
      {
       "expr": "(count(mikrotik_cloud_bth_vpn_relay_ipv6_reachable{dev_name=~\"$devname\"} == 1) / count(mikrotik_cloud_bth_vpn_relay_ipv6_reachable{dev_name=~\"$devname\"})) or vector(0)",
       "legendFormat": "IPv6"
      }
     ]
    },
    {
     "title": "Services active connections",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 2, "x": 8, "y": 139 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(service) (mikrotik_service_active_connections_count{dev_name=~\"$devname\"})",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Neighbours",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 2, "x": 10, "y": 139 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(mikrotik_neighbor_discovered{dev_name=~\"$devname\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "neighbor_entry",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(dev_name) (mikrotik_neighbor_discovered{dev_name=~\"$devname\"})",
       "legendFormat": "{{dev_name}}"
      }
     ]
    },
    {
     "title": "arp_entry",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
     "targets": [
      {
       "expr": "mikrotik_arp_status{dev_name=~\"$devname\",status!=\"failed\"}",
       "legendFormat": "{{dev_name}} {{status}}"
      },
      {
       "expr": "mikrotik_arp_invalid{dev_name=~\"$devname\"}",
       "legendFormat": "{{dev_name}} invalid"
      }
     ]
    },
    {
     "title": "conntrack_total_entries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "mikrotik_conntrack_total_entries{dev_name=~\"$devname\"}",
       "legendFormat": "{{dev_name}}"
      }
     ]
    },
    {
     "title": "FP/FT Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(mikrotik_ip_ipv4_fast_path_bytes_total{dev_name=~\"$devname\"}[5m])",
       "legendFormat": "FP bytes {{dev_name}}"
      },
      {
       "expr": "rate(mikrotik_ip_ipv4_fasttrack_bytes_total{dev_name=~\"$devname\"}[5m])",
       "legendFormat": "FT bytes {{dev_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IP DHCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "dhcp_leases_active",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 371 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mikrotik_dhcp_leases_active{dev_name=~\"$devname\"}",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Pool used",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 2, "x": 2, "y": 371 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mikrotik_ip_pool_used{dev_name=~\"$devname\"})/sum(mikrotik_ip_pool_total{dev_name=~\"$devname\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DHCP Lease statuses",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 371 },
     "targets": [
      {
       "expr": "mikrotik_dhcp_status{dev_name=~\"$devname\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "DHCP Lease active",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 631 },
     "targets": [
      {
       "expr": "mikrotik_dhcp_leases_active{dev_name=~\"$devname\"}",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IP DNS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNS Cache used",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 371 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mikrotik_dns_cache_used_bytes{dev_name=~\"$devname\"})/sum(mikrotik_dns_cache_size_bytes{dev_name=~\"$devname\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Adlist match",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 11, "y": 371 },
     "targets": [
      {
       "expr": "rate(mikrotik_dns_adlist_match_count_total{dev_name=~\"$devname\"}[$__rate_interval])",
       "legendFormat": "{{dev_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IP Firewall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes All Interfaces",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(mikrotik_firewall_bytes_total{dev_name=~\"$devname\"}[$__rate_interval]) > 0",
       "legendFormat": "{{firewall}}:{{chain}}"
      }
     ]
    },
    {
     "title": "Packets All Interfaces",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(mikrotik_firewall_packets_total{dev_name=~\"$devname\"}[$__rate_interval]) > 0",
       "legendFormat": "{{firewall}}:{{chain}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Capsman",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "WIFI Authorized clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 550 },
     "targets": [
      {
       "expr": "mikrotik_capsman_interface_current_authorized_clients{dev_name=~\"$devname\"} > 0",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "capsman radio provisioned",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 12, "y": 550 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(mikrotik_capsman_radio_provisioned{dev_name=~\"$devname\"} == 1) or vector(0)",
       "legendFormat": "provisioned"
      },
      {
       "expr": "count(mikrotik_capsman_radio_provisioned{dev_name=~\"$devname\"}) or vector(0)",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Capsman stations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 558 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count by(dev_name) (mikrotik_capsman_station_uptime_seconds{dev_name=~\"$devname\"})    ",
       "legendFormat": "{{dev_name}}"
      }
     ]
    },
    {
     "title": "Interface State",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 558 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "mikrotik_capsman_interface_state{dev_name=~\"$devname\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Capsman station RX/TX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 566 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(interface, ssid) (rate(mikrotik_capsman_station_rx_bytes_total{dev_name=~\"$devname\"}[$__rate_interval]))",
       "legendFormat": "rx {{interface}} {{ssid}}"
      },
      {
       "expr": "sum by(interface, ssid) (rate(mikrotik_capsman_station_tx_bytes_total{dev_name=~\"$devname\"}[$__rate_interval]))",
       "legendFormat": "tx {{interface}} {{ssid}}"
      }
     ]
    },
    {
     "title": "WIFI Registration",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 566 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "mikrotik_capsman_station_uptime_seconds{dev_name=~\"$devname\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "mikrotik_capsman_station_rx_signal{dev_name=~\"$devname\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Wireguard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wireguard",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 783 },
     "targets": [
      {
       "expr": "mikrotik_wireguard_running{dev_name=~\"$devname\"}",
       "legendFormat": "{{dev_name}}"
      }
     ]
    },
    {
     "title": "Connected peers",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 783 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(mikrotik_wireguard_peers_status{dev_name=~\"$devname\", status=\"connected\"}) or vector(0)",
       "legendFormat": "connected"
      },
      {
       "expr": "sum(mikrotik_wireguard_peers_status{dev_name=~\"$devname\"}) or vector(0)",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Wireguard Peers",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 788 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "mikrotik_wireguard_last_handshake{dev_name=~\"$devname\"}",
       "legendFormat": "{{name}} {{status}}"
      }
     ]
    },
    {
     "title": "Wireguard RX/TX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 788 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(mikrotik_wireguard_rx_total{dev_name=~\"$devname\"}[$__rate_interval])",
       "legendFormat": "rx {{dev_name}} {{comment}}"
      },
      {
       "expr": "rate(mikrotik_wireguard_tx_total{dev_name=~\"$devname\"}[$__rate_interval])",
       "legendFormat": "tx {{dev_name}} {{comment}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Simple queue bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 376 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(mikrotik_simple_queue_rx_bytes_total{dev_name=~\"$devname\"}[$__rate_interval])",
       "legendFormat": "rx {{dev_name}} {{simple_queue_name}}"
      },
      {
       "expr": "rate(mikrotik_simple_queue_tx_bytes_total{dev_name=~\"$devname\"}[$__rate_interval])",
       "legendFormat": "tx {{dev_name}} {{simple_queue_name}}"
      }
     ]
    },
    {
     "title": "Simple Queue Queded bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 376 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(mikrotik_simple_queue_rx_queued_bytes_total{dev_name=~\"$devname\"}[$__rate_interval])",
       "legendFormat": "rx {{dev_name}} {{simple_queue_name}}"
      },
      {
       "expr": "rate(mikrotik_simple_queue_tx_queued_bytes_total{dev_name=~\"$devname\"}[$__rate_interval])",
       "legendFormat": "tx {{dev_name}} {{simple_queue_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "NTP system offset",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "mikrotik_ntp_client_system_offset{dev_name=~\"$devname\"}",
       "legendFormat": "{{dev_name}}"
      }
     ]
    },
    {
     "title": "NTP synchronized",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(mikrotik_ntp_client_synchronized{dev_name=~\"$devname\"} == 1) or vector(0)",
       "legendFormat": "synchronized"
      },
      {
       "expr": "count(mikrotik_ntp_client_enabled{dev_name=~\"$devname\"}) or vector(0)",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "PPP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "PPP Active connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 833 },
     "targets": [
      {
       "expr": "mikrotik_ppp_active{dev_name=~\"$devname\"}",
       "legendFormat": "{{dev_name}}"
      }
     ]
    },
    {
     "title": "PPP Active peers",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 833 },
     "targets": [
      { "expr": "mikrotik_ppp_active_peer", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  { "title": "Switch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Driver Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(mikrotik_switch_driver_rx_byte_total{dev_name=~\"$devname\"}[$__rate_interval]))",
     "legendFormat": "rx"
    },
    {
     "expr": "sum(rate(mikrotik_switch_driver_tx_byte_total{dev_name=~\"$devname\"}[$__rate_interval]))",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Driver Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(mikrotik_switch_driver_rx_packet_total{dev_name=~\"$devname\"}[$__rate_interval]))",
     "legendFormat": "rx"
    },
    {
     "expr": "sum(rate(mikrotik_switch_driver_tx_packet_total{dev_name=~\"$devname\"}[$__rate_interval]))",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(mikrotik_switch_rx_bytes_total{dev_name=~\"$devname\"}[$__rate_interval]))   ",
     "legendFormat": "rx"
    },
    {
     "expr": "rate(mikrotik_switch_tx_bytes_total{dev_name=~\"$devname\"}[$__rate_interval])",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(mikrotik_switch_rx_packet_total{dev_name=~\"$devname\"}[$__rate_interval]))",
     "legendFormat": "rx"
    },
    {
     "expr": "sum(rate(mikrotik_switch_tx_packet_total{dev_name=~\"$devname\"}[$__rate_interval]))",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Packets drop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(mikrotik_switch_rx_drop_total{dev_name=~\"$devname\"}[$__rate_interval]))",
     "legendFormat": "rc"
    },
    {
     "expr": "sum(rate(mikrotik_switch_tx_total{dev_name=~\"$devname\"}[$__rate_interval]))",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Broadcast / multicast",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(mikrotik_switch_rx_broadcast_total{dev_name=~\"$devname\"}[$__rate_interval]))",
     "legendFormat": "rx broadcast"
    },
    {
     "expr": "sum(rate(mikrotik_switch_rx_multicast_total{dev_name=~\"$devname\"}[$__rate_interval]))",
     "legendFormat": "rx multicast"
    },
    {
     "expr": "sum(rate(mikrotik_switch_tx_broadcast_total{dev_name=~\"$devname\"}[$__rate_interval]))",
     "legendFormat": "tx broadcast"
    },
    {
     "expr": "sum(rate(mikrotik_switch_tx_multicast_total{dev_name=~\"$devname\"}[$__rate_interval]))",
     "legendFormat": "tx multicast"
    }
   ]
  },
  {
   "title": "Interface $devname $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "repeat": "interface",
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 877 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(mikrotik_interface_rx_byte_total{interface=~\"$interface\", dev_name=~\"$devname\"}[$__rate_interval])",
       "legendFormat": "rx {{dev_name}} {{interface}}"
      },
      {
       "expr": "rate(mikrotik_interface_tx_byte_total{interface=~\"$interface\", dev_name=~\"$devname\"}[$__rate_interval])",
       "legendFormat": "tx {{dev_name}} {{interface}}"
      }
     ]
    },
    {
     "title": "Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 877 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(mikrotik_interface_rx_packet_total{interface=~\"$interface\", dev_name=~\"$devname\"}[$__rate_interval])",
       "legendFormat": "rx {{dev_name}} {{interface}}"
      },
      {
       "expr": "rate(mikrotik_interface_tx_packet_total{interface=~\"$interface\", dev_name=~\"$devname\"}[$__rate_interval])",
       "legendFormat": "tx {{dev_name}} {{interface}}"
      }
     ]
    },
    {
     "title": "Drop",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 885 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(mikrotik_interface_rx_drop_total{interface=~\"$interface\", dev_name=~\"$devname\"}[$__rate_interval])",
       "legendFormat": "rx drop {{dev_name}} {{interface}}"
      },
      {
       "expr": "rate(mikrotik_interface_tx_drop_total{interface=~\"$interface\", dev_name=~\"$devname\"}[$__rate_interval])",
       "legendFormat": "tx drop {{dev_name}} {{interface}}"
      },
      {
       "expr": "rate(mikrotik_interface_tx_queue_drop_total{interface=~\"$interface\", dev_name=~\"$devname\"}[$__rate_interval])",
       "legendFormat": "tx queue drop {{dev_name}} {{interface}}"
      }
     ]
    },
    {
     "title": "Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 885 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(mikrotik_interface_rx_error_total{interface=~\"$interface\", dev_name=~\"$devname\"}[$__rate_interval])",
       "legendFormat": "rx {{dev_name}} {{interface}}"
      },
      {
       "expr": "rate(mikrotik_interface_tx_error_total{interface=~\"$interface\", dev_name=~\"$devname\"}[$__rate_interval])",
       "legendFormat": "tx {{dev_name}} {{interface}}"
      }
     ]
    },
    {
     "title": "Link downs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 893 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mikrotik_interface_link_downs_total{interface=~\"$interface\", dev_name=~\"$devname\"}",
       "legendFormat": "in {{name}} {{interface}}"
      }
     ]
    },
    {
     "title": "MTU",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 893 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mikrotik_interface_actual_mtu{interface=~\"$interface\", dev_name=~\"$devname\"}",
       "legendFormat": "in {{name}} {{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scrape duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1866 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "mikrotik_scrape_device_duration_seconds{dev_name=~\"$devname\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scrape errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1866 },
     "targets": [
      {
       "expr": "rate(mikrotik_scrape_device_errors_total{dev_name=~\"$devname\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}