devices:
  - name: test1
    address: 192.168.1.1
    user: foo
    password: bar
  - name: test2
    address: 192.168.2.1
    user: test
    password: 123
  - name: testProfileMinimal
    address: 192.168.2.1
    user: test
    password: 123
    profile: minimal
  - name: testProfileBasic
    address: 192.168.2.1
    user: test
    password: 123
    profile: basic
    # default
    disabled: false
  - name: testService
    user: test
    password: 123
    srv:
      record: record1
  - name: testDns
    user: test
    password: 123
    srv:
      record: record2
      dns:
        address: dnsaddress
        port: 1053


features:
  conntrack: true
  dhcp: true
  dhcpl: true
  dhcpv6: true
  ipsec: true
  lte:
    settings1: 123
    settings2: "abc"
  netwatch: true
  optics: true
  pools: true
  queue: true
  routes: true
  wlanif: true
  wlansta: true


profiles:
  all:
    capsman: true
    conntrack: true
    dhcp: true
    dhcpl: true
    dhcpv6: true
    firmware: true
    health: true
    ipsec: true
    lte:
    monitor: true
    netwatch: true
    optics: true
    poe: true
    pools: true
    queue: true
    routes: true
    w60g: true
    wlanif: true
    wlansta: true
  minimal:
    firmware: true
    health: true
    monitor: true
  basic:
    dhcp: true
    dhcpl: true
    firmware: true
    health: true
    monitor: true
    routes:
      enabled: true
    wlanif:
    wlansta:
      enabled: false
